### ISSUE TITLE
Is this project no longer maintained? Dependencies are not updated

### ISSUE THREAD

**Issue by undergroundwires** [vuejs/eslint-config-airbnb#67]
There are important issues such as #65 #63 that's blocking updating a lot of dependencies.
This project has become liability for many.

- Can we get an official announcement if this project is no longer maintained, so we can go for alternative solutions? @sodatea
- If the project is not decided to be archived, can we at least get documentation how to update these dependencies so this package becomes no longer a liability? I see that @satouriko did this a year ago in #61 but this is needed again. Can @satouriko or @sodatea help?
- Is there anyone that has found any other solution to these problems?

It blocks many other dependencies:

![image](https://github.com/user-attachments/assets/ad09ca4b-65eb-4406-a60c-ff3445422855)

**Comment by haoqunjiang** [comment]
I'm working towards it. But it takes a tremendous amount of time and effort to adapt to ESLint 9 so don't expect anything anytime soon. Not to say that both of the two major upstream dependencies (`eslint-config-airbnb-base` and `eslint-config-airbnb-typescript`) haven't achieved compatibility with ESLint 9 yet.

Come on, it's only 10 months since the last major version bump. Why would you call such a project abandoned?

**Comment by danielwwc** [comment]
`eslint-config-airbnb` and `eslint-config-airbnb-base` haven't had any release since 3 years.
`eslint-config-airbnb-typescript` repository been archived by the owner on Aug 14, 2024. 

It will take huge effort to adapt to first adapt @typescript-eslint/parser v8 and eslint 9.
Appreciate and thanks for the effort to make it works, however the`eslint-config-airbnb` is considered abandoned

**Comment by undergroundwires** [comment]
I'm sorry if I come across negative here, and thank you for informing that it's still in maintenance.
I consider the project active until not announced officially that it's dead.

It's said that the upstream projects are no longer maintained.
It would be totally understand that you'd decide to archive this project too.

In that case, any guidance would be highly appreciated suggesting a migration path to good alternative.
